### ISSUE TITLE
1.0.45 package is corrupt

### ISSUE THREAD

**Issue by daveio** [sandipchitale/vscode-kubernetes-helm-extras#3]
The package might need to be rebuilt and reuploaded.

```
2023-03-15 03:22:01.263 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

**Comment by sandipchitale** [comment]
Let me look into it.

**Comment by sandipchitale** [comment]
@daveio Please try 1.0.46
